//
//  ProfileWorker.swift
//  bitnance assignment
//
//  Created by Wisarut Multhonggad on 5/1/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya
import Moya_ObjectMapper

class ProfileWorker
{
    fileprivate let provider = MoyaProvider<NewsServive>()
    
    func getTopHeadlinesNews() -> Single<News> {
        let body = ["country": "us",
                    "category": "business",
                    "apiKey": AppDelegate.apiKey ?? ""] as [String: Any]
        return provider.rx.request(.getTopHeadlinesNews(body: body)).mapObject(News.self)
    }
}
